name: caishen_wallet
description: Spending tracker.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  google_fonts: ^2.3.1
  liquid_progress_indicator: ^0.4.0
  provider: ^6.0.2

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
