name: caishen_wallet
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  app_tracking_transparency: ^2.0.2+1
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  google_fonts: ^2.3.1
  provider: ^6.0.2

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true

  # Access .env file:
  ## import 'package:flutter_dotenv/flutter_dotenv.dart';
  ## dotenv.env['VAR_NAME'];
  assets:
    - assets/lang/
